### ISSUE TITLE
Stellaris :: Blender 2.8+ :: New "Frame" Mesh types missing objects

### ISSUE THREAD

**Issue by Tetrino** [ross-g/io_pdx_mesh#21]
Hey Ross, great work on this plugin, I've been using it to throw together some things.

I've noticed that on the two newest ship sets (that is, Lithoids and Necroids) and some ship types (all Titan class ships) the "frame" import appears to be missing some relevant data. I believe this to be down to Paradox subtly changing the format and may need updating your end (unfortunately I have no way of reading the .mesh format directly to be sure).

To fill you in brief, these mesh files (e.g. `\Stellaris\gfx\models\ships\mammalian_01\mammalian_01_battleship_frame.mesh`) contain information pertaining to the location of each given segment of a ship type in relation to each other on any ship with three segments. Cruisers, Battleships and Titans have these meshes. You almost certainly already knew this but it's important for the framing.

In all ship sets including the Humanoid and Plantoid addons, the `frame` mesh is imported as a series of locator empties and an armature including three bones. The typical layout for a given ship frame when it works as expected is:

```
io_pdx_rig
--Pose
--Imported_armature (which may or may not be linked to the locator transforms below, seems it should be linked?)
----(skipped for brevity)
--Explosion_locators (multiple, skipped for brevity)
--part1_locator
--part2_back_locator
--part2_front_locator
--part3_locator
```

However for the newest two ship additions we do not have this structure, in fact it appears it's missing or corrupted. The one instance I've found where we do have a locator (`necroid_01_battleship_frame.mesh`) it's `part2_back` and is given the wonderful maximised `y` position of `831690816 m` and the `xyz` scale of `100000000` on all axis.

**Edit:** Seems that Humanoid ships are also corrupted, so we get all the locators but their locations are wrong.

It's the fact these values are maximised which makes me think it's a format issue. I'd submit a PR but I'm not too comfortable with Python, let alone Blender scripts.

Let me know if there is anything I can do to help here.
Thanks.

**Comment by Tetrino** [comment]
I want to add that I know this is a universal tool, so I'm not expecting exclusions or anything for this. If it's unfixed it's unfixed, I'm just wondering if internally they're doing more with these or it's a sign of an updated schema.

**Comment by ross-g** [comment]
Hey, thanks for the detailed report and explaination! I'm afraid I don't have Necroids to check the content out, but I do have the Lithoids DLC (it rocks!) so I will investigate the frame meshes for that ship set to see if I can reproduce the problem.

I have just tried the Humanoid cruiser (humanoid_01_cruiser_frame.mesh) and that definitely does show the issue. So I'll let you know what I find.

**Comment by Tetrino** [comment]
Cheers Ross, anything I can do to help let me know!

**Comment by ross-g** [comment]
Just a quick update, as I've tracked this down now. 

The problem here is due to locators being parented to bones, where those bones have a zero-scale transform. Normally when applying the parent transform to a locator it will compensate for parent scale (ie if parent is at 50% scale, you double the locator scale). Obviously you can't compensate for a scale of 0... so you get ludicrous transforms on the locators.

This is already handled for bones so should be an easy fix.

**Comment by Tetrino** [comment]
Bit late on seeing this my end - good to hear it's an easy fix. Seems like an odd decision their end but I suppose if they don't need the transform on those particular bones it makes sense.

**Comment by ross-g** [comment]
Fixed by b886a05c50df97b01fd51e4bfd9f5eda2d1f96af in the bugfixes branch.
This issue will be closed once the fix is in a release.

**Comment by Tetrino** [comment]
Sorry @ross-g seems not quite there. Tried it on the bugfix branch and recieve the following error:

```Traceback (most recent call last):
  File "C:\Users\Moose\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_pdx_mesh\pdx_blender\blender_ui.py", line 361, in execute
    bonespace=self.chk_bonespace,
  File "C:\Users\Moose\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_pdx_mesh\pdx_blender\blender_import_export.py", line 1224, in import_meshfile
    obj = create_locator(pdx_locator, scene_bone_dict)
  File "C:\Users\Moose\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_pdx_mesh\pdx_blender\blender_import_export.py", line 772, in create_locator
    parent_Xform = Matrix.Scale(1.0 / scale[0], 4) @ mat
NameError: name 'mat' is not defined

location: <unknown location>:-1```

I figure you'll see this and :homer_doh: - it only affects the new fix, it's a regression in that previous working _frame meshes now do not work, but it does not affect anything outside of said _frame meshes. I saw this really late my time so couldn't troubleshoot a fix sorry.

**Comment by ross-g** [comment]
Thanks for testing, always appreciated! Just a dumb copy/paste error on my part, should now be fixed.

**Comment by Tetrino** [comment]
Further testing on the latest debug branch and we still have the same issue of missing parts for ships (lithoids/titans/necroids), though we now have explosion locators and target locators in the correct places.

I know I'm likely the only one using these meshes so I'm going to fork a branch and see what I can do (about time I added Python/Blender debugging to my knowledge anyway). Don't want to waste your time on this.

Oddly on the one mesh that always loaded the locator, just in the wrong place, it now loads in the correct place ( `necroid_01_battleship_frame.mesh` ) so the fix is definitely doing *something*, I'll just have to dig and see if those things even exist in these meshes as normal or if Paradox changed things entirely.

**Comment by Tetrino** [comment]
Alright I took a real deep dive into the new models and they don't have any locators at all in the usual places. It's very damn strange!

So for now this is **fixed** and I'll see what I can do to find these things, as they must be somewhere else the game wouldn't sync them up correctly.

**Comment by ross-g** [comment]
Great to hear, thanks for the feedback. I got worried when I saw this issue had 3 more replies 😆 but good to know it's working.

I have no idea why these mesh files have zero scale bones, especially as the idle animation then goes on to correct that. I suspect it was just a cockup at PDX when exporting the mesh.

**Comment by ross-g** [comment]
Fixed in 0.8 release. (364800cff10bdc822429ec73149cadcb05ef9710)
